In [1]:
# To Install Kaggle
#!pip install kaggle

In [16]:
# Importing Kaggle library

#Extract
import kaggle

In [17]:
#Downloading dataset from kaggle
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [18]:
#extract file from zip file
import zipfile

zip_ref = zipfile.ZipFile('orders.csv.zip') # if the location is different we need to pass the location
zip_ref.extractall() # extract file to dir
zip_ref.close() # closing file

In [19]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\ladia\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ladia\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ladia\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ladia\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ladia\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\ladia\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [20]:
#Transform

import pandas as pd

#Gathering CSV data
orders_data=pd.read_csv('orders.csv')
#orders_data.head(20)

#What I observed?
# 1) Observed Ship Mode column consists of 3 Types of null values ( Not Available, Null,unknown)
# 2) Convert Column names to lower case and need to replace the spaces with underscore
orders_data['Ship Mode'].unique() #array(['Second Class', 'Standard Class', 'Not Available', 'unknown','First Class', nan, 'Same Day'], dtype=object)
#Observed Ship Mode column consists of 3 Types of null values ( Not Available, Null,unknown)
#Planning to remove them while csv data loading

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

In [21]:
orders_data=pd.read_csv('orders.csv',na_values=['Not Available','unknown'])
orders_data['Ship Mode'].unique()
#Output : array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],dtype=object)

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [22]:
# 2) Convert Column names to lower case and need to replace the spaces with underscore
orders_data.columns

'''Output : Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent'],
      dtype='object')'''

"Output : Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',\n       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',\n       'Product Id', 'cost price', 'List Price', 'Quantity',\n       'Discount Percent'],\n      dtype='object')"

In [23]:
orders_data.columns=orders_data.columns.str.lower()

In [24]:
orders_data.columns=orders_data.columns.str.replace(' ','_')

In [25]:
orders_data

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [26]:
#datatype conversion
#orders_data.dtypes
#Need to convert order_date from object to Date
orders_data['order_date']=pd.to_datetime(orders_data['order_date'],format="%Y-%m-%d")

In [27]:
#Here we have Discount% but there is not sale_price,need to find that
orders_data['discount']=orders_data['list_price']*orders_data['discount_percent']*0.01
orders_data['sale_price']=orders_data['list_price']-orders_data['discount']

#Profit
orders_data['profit']=orders_data['sale_price']-orders_data['cost_price']

In [28]:
orders_data

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [29]:
#dropping the columns which are not required
orders_data.drop(columns=['list_price','cost_price','discount_percent'],inplace=True)

In [30]:
orders_data

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [31]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\ladia\appdata\local\programs\python\python312\lib\site-packages (2.0.30)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ladia\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ladia\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.0.3)

In [32]:
!pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\ladia\appdata\local\programs\python\python312\lib\site-packages (5.1.0)

In [1]:
#Load

import sqlalchemy as sal
conn = sal.create_engine('mssql://ASHRITH\\sqlexpress/SQL_Learning?driver=ODBC+DRIVER+17+FOR+SQL+SERVER').connect()


#load the data into sql server using append option
orders_data.to_sql('orders_data', con=conn , index=False, if_exists = 'replace')

NameError: name 'sal' is not defined